package edu.uv.modelo.pojos.admproy;
// Generated 27/05/2014 12:50:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Academico generated by hbm2java
 */
public class Academico  implements java.io.Serializable {


     private Integer idAcademico;
     private int remunerado;
     private int tipoAcademico;
     private String tipo;
     private Set experienciaacademicas = new HashSet(0);
     private Set escolaridads = new HashSet(0);
     private Set idiomases = new HashSet(0);
     private Set distincioneses = new HashSet(0);
     private Set experiencialaborals = new HashSet(0);
     private Set datossintesises = new HashSet(0);
     private Set datosactoacademicos = new HashSet(0);

    public Academico() {
    }

	
    public Academico(int remunerado, int tipoAcademico) {
        this.remunerado = remunerado;
        this.tipoAcademico = tipoAcademico;
    }
    public Academico(int remunerado, int tipoAcademico, String tipo, Set experienciaacademicas, Set escolaridads, Set idiomases, Set distincioneses, Set experiencialaborals, Set datossintesises, Set datosactoacademicos) {
       this.remunerado = remunerado;
       this.tipoAcademico = tipoAcademico;
       this.tipo = tipo;
       this.experienciaacademicas = experienciaacademicas;
       this.escolaridads = escolaridads;
       this.idiomases = idiomases;
       this.distincioneses = distincioneses;
       this.experiencialaborals = experiencialaborals;
       this.datossintesises = datossintesises;
       this.datosactoacademicos = datosactoacademicos;
    }
   
    public Integer getIdAcademico() {
        return this.idAcademico;
    }
    
    public void setIdAcademico(Integer idAcademico) {
        this.idAcademico = idAcademico;
    }
    public int getRemunerado() {
        return this.remunerado;
    }
    
    public void setRemunerado(int remunerado) {
        this.remunerado = remunerado;
    }
    public int getTipoAcademico() {
        return this.tipoAcademico;
    }
    
    public void setTipoAcademico(int tipoAcademico) {
        this.tipoAcademico = tipoAcademico;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getExperienciaacademicas() {
        return this.experienciaacademicas;
    }
    
    public void setExperienciaacademicas(Set experienciaacademicas) {
        this.experienciaacademicas = experienciaacademicas;
    }
    public Set getEscolaridads() {
        return this.escolaridads;
    }
    
    public void setEscolaridads(Set escolaridads) {
        this.escolaridads = escolaridads;
    }
    public Set getIdiomases() {
        return this.idiomases;
    }
    
    public void setIdiomases(Set idiomases) {
        this.idiomases = idiomases;
    }
    public Set getDistincioneses() {
        return this.distincioneses;
    }
    
    public void setDistincioneses(Set distincioneses) {
        this.distincioneses = distincioneses;
    }
    public Set getExperiencialaborals() {
        return this.experiencialaborals;
    }
    
    public void setExperiencialaborals(Set experiencialaborals) {
        this.experiencialaborals = experiencialaborals;
    }
    public Set getDatossintesises() {
        return this.datossintesises;
    }
    
    public void setDatossintesises(Set datossintesises) {
        this.datossintesises = datossintesises;
    }
    public Set getDatosactoacademicos() {
        return this.datosactoacademicos;
    }
    
    public void setDatosactoacademicos(Set datosactoacademicos) {
        this.datosactoacademicos = datosactoacademicos;
    }




}


