package edu.uv.modelo.pojos.admproy;
// Generated 27/05/2014 12:50:36 PM by Hibernate Tools 3.6.0



/**
 * Datossintesis generated by hbm2java
 */
public class Datossintesis  implements java.io.Serializable {


     private int idDatoGralSintesis;
     private Idiomas idiomas;
     private Experienciaacademica experienciaacademica;
     private Experiencialaboral experiencialaboral;
     private Distinciones distinciones;
     private Academico academico;
     private Escolaridad escolaridad;
     private int funcionAcad;

    public Datossintesis() {
    }

    public Datossintesis(int idDatoGralSintesis, Idiomas idiomas, Experienciaacademica experienciaacademica, Experiencialaboral experiencialaboral, Distinciones distinciones, Academico academico, Escolaridad escolaridad, int funcionAcad) {
       this.idDatoGralSintesis = idDatoGralSintesis;
       this.idiomas = idiomas;
       this.experienciaacademica = experienciaacademica;
       this.experiencialaboral = experiencialaboral;
       this.distinciones = distinciones;
       this.academico = academico;
       this.escolaridad = escolaridad;
       this.funcionAcad = funcionAcad;
    }
   
    public int getIdDatoGralSintesis() {
        return this.idDatoGralSintesis;
    }
    
    public void setIdDatoGralSintesis(int idDatoGralSintesis) {
        this.idDatoGralSintesis = idDatoGralSintesis;
    }
    public Idiomas getIdiomas() {
        return this.idiomas;
    }
    
    public void setIdiomas(Idiomas idiomas) {
        this.idiomas = idiomas;
    }
    public Experienciaacademica getExperienciaacademica() {
        return this.experienciaacademica;
    }
    
    public void setExperienciaacademica(Experienciaacademica experienciaacademica) {
        this.experienciaacademica = experienciaacademica;
    }
    public Experiencialaboral getExperiencialaboral() {
        return this.experiencialaboral;
    }
    
    public void setExperiencialaboral(Experiencialaboral experiencialaboral) {
        this.experiencialaboral = experiencialaboral;
    }
    public Distinciones getDistinciones() {
        return this.distinciones;
    }
    
    public void setDistinciones(Distinciones distinciones) {
        this.distinciones = distinciones;
    }
    public Academico getAcademico() {
        return this.academico;
    }
    
    public void setAcademico(Academico academico) {
        this.academico = academico;
    }
    public Escolaridad getEscolaridad() {
        return this.escolaridad;
    }
    
    public void setEscolaridad(Escolaridad escolaridad) {
        this.escolaridad = escolaridad;
    }
    public int getFuncionAcad() {
        return this.funcionAcad;
    }
    
    public void setFuncionAcad(int funcionAcad) {
        this.funcionAcad = funcionAcad;
    }




}


