package edu.uv.modelo.pojos.admproy;
// Generated 27/05/2014 12:50:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Datoscurso generated by hbm2java
 */
public class Datoscurso  implements java.io.Serializable {


     private Integer idExperiencia;
     private Datosactoacademico datosactoacademico;
     private int creditos;
     private String descripcion;
     private Set datosalumnos = new HashSet(0);

    public Datoscurso() {
    }

	
    public Datoscurso(Datosactoacademico datosactoacademico, int creditos, String descripcion) {
        this.datosactoacademico = datosactoacademico;
        this.creditos = creditos;
        this.descripcion = descripcion;
    }
    public Datoscurso(Datosactoacademico datosactoacademico, int creditos, String descripcion, Set datosalumnos) {
       this.datosactoacademico = datosactoacademico;
       this.creditos = creditos;
       this.descripcion = descripcion;
       this.datosalumnos = datosalumnos;
    }
   
    public Integer getIdExperiencia() {
        return this.idExperiencia;
    }
    
    public void setIdExperiencia(Integer idExperiencia) {
        this.idExperiencia = idExperiencia;
    }
    public Datosactoacademico getDatosactoacademico() {
        return this.datosactoacademico;
    }
    
    public void setDatosactoacademico(Datosactoacademico datosactoacademico) {
        this.datosactoacademico = datosactoacademico;
    }
    public int getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(int creditos) {
        this.creditos = creditos;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getDatosalumnos() {
        return this.datosalumnos;
    }
    
    public void setDatosalumnos(Set datosalumnos) {
        this.datosalumnos = datosalumnos;
    }




}


