package edu.uv.modelo.pojos.admproy;
// Generated 27/05/2014 12:50:36 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Datosevaluacion generated by hbm2java
 */
public class Datosevaluacion  implements java.io.Serializable {


     private int idDatosEvaluacion;
     private Datosactoacademico datosactoacademico;
     private String nomProfesor;
     private String medio;
     private String capacidad;
     private String conocimiento;
     private String usoApoyos;
     private String habilidadpedagogica;
     private String manejoTiempo;
     private String conceptos;
     private String congruencia;
     private String calidadMaterial;
     private String condicionAula;
     private String servicioSanitario;
     private String personalEncargado;
     private String calidadImpresion;
     private String congruenciaRevisado;
     private int calificacionGeneral;
     private int calificacionDesempeño;
     private String elevarNivelCurso;
     private int curso;
     private String observaciones;
     private Date fecha;

    public Datosevaluacion() {
    }

    public Datosevaluacion(int idDatosEvaluacion, Datosactoacademico datosactoacademico, String nomProfesor, String medio, String capacidad, String conocimiento, String usoApoyos, String habilidadpedagogica, String manejoTiempo, String conceptos, String congruencia, String calidadMaterial, String condicionAula, String servicioSanitario, String personalEncargado, String calidadImpresion, String congruenciaRevisado, int calificacionGeneral, int calificacionDesempeño, String elevarNivelCurso, int curso, String observaciones, Date fecha) {
       this.idDatosEvaluacion = idDatosEvaluacion;
       this.datosactoacademico = datosactoacademico;
       this.nomProfesor = nomProfesor;
       this.medio = medio;
       this.capacidad = capacidad;
       this.conocimiento = conocimiento;
       this.usoApoyos = usoApoyos;
       this.habilidadpedagogica = habilidadpedagogica;
       this.manejoTiempo = manejoTiempo;
       this.conceptos = conceptos;
       this.congruencia = congruencia;
       this.calidadMaterial = calidadMaterial;
       this.condicionAula = condicionAula;
       this.servicioSanitario = servicioSanitario;
       this.personalEncargado = personalEncargado;
       this.calidadImpresion = calidadImpresion;
       this.congruenciaRevisado = congruenciaRevisado;
       this.calificacionGeneral = calificacionGeneral;
       this.calificacionDesempeño = calificacionDesempeño;
       this.elevarNivelCurso = elevarNivelCurso;
       this.curso = curso;
       this.observaciones = observaciones;
       this.fecha = fecha;
    }
   
    public int getIdDatosEvaluacion() {
        return this.idDatosEvaluacion;
    }
    
    public void setIdDatosEvaluacion(int idDatosEvaluacion) {
        this.idDatosEvaluacion = idDatosEvaluacion;
    }
    public Datosactoacademico getDatosactoacademico() {
        return this.datosactoacademico;
    }
    
    public void setDatosactoacademico(Datosactoacademico datosactoacademico) {
        this.datosactoacademico = datosactoacademico;
    }
    public String getNomProfesor() {
        return this.nomProfesor;
    }
    
    public void setNomProfesor(String nomProfesor) {
        this.nomProfesor = nomProfesor;
    }
    public String getMedio() {
        return this.medio;
    }
    
    public void setMedio(String medio) {
        this.medio = medio;
    }
    public String getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(String capacidad) {
        this.capacidad = capacidad;
    }
    public String getConocimiento() {
        return this.conocimiento;
    }
    
    public void setConocimiento(String conocimiento) {
        this.conocimiento = conocimiento;
    }
    public String getUsoApoyos() {
        return this.usoApoyos;
    }
    
    public void setUsoApoyos(String usoApoyos) {
        this.usoApoyos = usoApoyos;
    }
    public String getHabilidadpedagogica() {
        return this.habilidadpedagogica;
    }
    
    public void setHabilidadpedagogica(String habilidadpedagogica) {
        this.habilidadpedagogica = habilidadpedagogica;
    }
    public String getManejoTiempo() {
        return this.manejoTiempo;
    }
    
    public void setManejoTiempo(String manejoTiempo) {
        this.manejoTiempo = manejoTiempo;
    }
    public String getConceptos() {
        return this.conceptos;
    }
    
    public void setConceptos(String conceptos) {
        this.conceptos = conceptos;
    }
    public String getCongruencia() {
        return this.congruencia;
    }
    
    public void setCongruencia(String congruencia) {
        this.congruencia = congruencia;
    }
    public String getCalidadMaterial() {
        return this.calidadMaterial;
    }
    
    public void setCalidadMaterial(String calidadMaterial) {
        this.calidadMaterial = calidadMaterial;
    }
    public String getCondicionAula() {
        return this.condicionAula;
    }
    
    public void setCondicionAula(String condicionAula) {
        this.condicionAula = condicionAula;
    }
    public String getServicioSanitario() {
        return this.servicioSanitario;
    }
    
    public void setServicioSanitario(String servicioSanitario) {
        this.servicioSanitario = servicioSanitario;
    }
    public String getPersonalEncargado() {
        return this.personalEncargado;
    }
    
    public void setPersonalEncargado(String personalEncargado) {
        this.personalEncargado = personalEncargado;
    }
    public String getCalidadImpresion() {
        return this.calidadImpresion;
    }
    
    public void setCalidadImpresion(String calidadImpresion) {
        this.calidadImpresion = calidadImpresion;
    }
    public String getCongruenciaRevisado() {
        return this.congruenciaRevisado;
    }
    
    public void setCongruenciaRevisado(String congruenciaRevisado) {
        this.congruenciaRevisado = congruenciaRevisado;
    }
    public int getCalificacionGeneral() {
        return this.calificacionGeneral;
    }
    
    public void setCalificacionGeneral(int calificacionGeneral) {
        this.calificacionGeneral = calificacionGeneral;
    }
    public int getCalificacionDesempeño() {
        return this.calificacionDesempeño;
    }
    
    public void setCalificacionDesempeño(int calificacionDesempeño) {
        this.calificacionDesempeño = calificacionDesempeño;
    }
    public String getElevarNivelCurso() {
        return this.elevarNivelCurso;
    }
    
    public void setElevarNivelCurso(String elevarNivelCurso) {
        this.elevarNivelCurso = elevarNivelCurso;
    }
    public int getCurso() {
        return this.curso;
    }
    
    public void setCurso(int curso) {
        this.curso = curso;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


