package edu.uv.modelo.pojos.admproy;
// Generated 27/05/2014 12:50:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Datosalumno generated by hbm2java
 */
public class Datosalumno  implements java.io.Serializable {


     private Integer idDatosAlumno;
     private String cursoInscrito;
     private String tipo;
     private String matricula;
     private Set datoscursos = new HashSet(0);

    public Datosalumno() {
    }

    public Datosalumno(String cursoInscrito, String tipo, String matricula, Set datoscursos) {
       this.cursoInscrito = cursoInscrito;
       this.tipo = tipo;
       this.matricula = matricula;
       this.datoscursos = datoscursos;
    }
   
    public Integer getIdDatosAlumno() {
        return this.idDatosAlumno;
    }
    
    public void setIdDatosAlumno(Integer idDatosAlumno) {
        this.idDatosAlumno = idDatosAlumno;
    }
    public String getCursoInscrito() {
        return this.cursoInscrito;
    }
    
    public void setCursoInscrito(String cursoInscrito) {
        this.cursoInscrito = cursoInscrito;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public Set getDatoscursos() {
        return this.datoscursos;
    }
    
    public void setDatoscursos(Set datoscursos) {
        this.datoscursos = datoscursos;
    }




}


