package edu.uv.modelo.pojos.admproy;
// Generated 27/05/2014 12:50:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Distinciones generated by hbm2java
 */
public class Distinciones  implements java.io.Serializable {


     private int iddistinciones;
     private Academico academico;
     private String nomDistincion;
     private String institucion;
     private Set datossintesises = new HashSet(0);

    public Distinciones() {
    }

	
    public Distinciones(int iddistinciones, Academico academico, String nomDistincion, String institucion) {
        this.iddistinciones = iddistinciones;
        this.academico = academico;
        this.nomDistincion = nomDistincion;
        this.institucion = institucion;
    }
    public Distinciones(int iddistinciones, Academico academico, String nomDistincion, String institucion, Set datossintesises) {
       this.iddistinciones = iddistinciones;
       this.academico = academico;
       this.nomDistincion = nomDistincion;
       this.institucion = institucion;
       this.datossintesises = datossintesises;
    }
   
    public int getIddistinciones() {
        return this.iddistinciones;
    }
    
    public void setIddistinciones(int iddistinciones) {
        this.iddistinciones = iddistinciones;
    }
    public Academico getAcademico() {
        return this.academico;
    }
    
    public void setAcademico(Academico academico) {
        this.academico = academico;
    }
    public String getNomDistincion() {
        return this.nomDistincion;
    }
    
    public void setNomDistincion(String nomDistincion) {
        this.nomDistincion = nomDistincion;
    }
    public String getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }
    public Set getDatossintesises() {
        return this.datossintesises;
    }
    
    public void setDatossintesises(Set datossintesises) {
        this.datossintesises = datossintesises;
    }




}


