package edu.uv.modelo.pojos.admproy;
// Generated 27/05/2014 12:50:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Escolaridad generated by hbm2java
 */
public class Escolaridad  implements java.io.Serializable {


     private int idescolaridad;
     private Academico academico;
     private String nomescolaridad;
     private String institucion;
     private Set datossintesises = new HashSet(0);

    public Escolaridad() {
    }

	
    public Escolaridad(int idescolaridad, Academico academico, String nomescolaridad, String institucion) {
        this.idescolaridad = idescolaridad;
        this.academico = academico;
        this.nomescolaridad = nomescolaridad;
        this.institucion = institucion;
    }
    public Escolaridad(int idescolaridad, Academico academico, String nomescolaridad, String institucion, Set datossintesises) {
       this.idescolaridad = idescolaridad;
       this.academico = academico;
       this.nomescolaridad = nomescolaridad;
       this.institucion = institucion;
       this.datossintesises = datossintesises;
    }
   
    public int getIdescolaridad() {
        return this.idescolaridad;
    }
    
    public void setIdescolaridad(int idescolaridad) {
        this.idescolaridad = idescolaridad;
    }
    public Academico getAcademico() {
        return this.academico;
    }
    
    public void setAcademico(Academico academico) {
        this.academico = academico;
    }
    public String getNomescolaridad() {
        return this.nomescolaridad;
    }
    
    public void setNomescolaridad(String nomescolaridad) {
        this.nomescolaridad = nomescolaridad;
    }
    public String getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }
    public Set getDatossintesises() {
        return this.datossintesises;
    }
    
    public void setDatossintesises(Set datossintesises) {
        this.datossintesises = datossintesises;
    }




}


