package edu.uv.modelo.pojos.admproy;
// Generated 27/05/2014 12:50:36 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Experienciaacademica generated by hbm2java
 */
public class Experienciaacademica  implements java.io.Serializable {


     private Integer idexperienciaAcademica;
     private Academico academico;
     private String materia;
     private Date año;
     private String semestre;
     private String institucion;
     private Set datossintesises = new HashSet(0);

    public Experienciaacademica() {
    }

	
    public Experienciaacademica(Academico academico, String materia, Date año, String semestre, String institucion) {
        this.academico = academico;
        this.materia = materia;
        this.año = año;
        this.semestre = semestre;
        this.institucion = institucion;
    }
    public Experienciaacademica(Academico academico, String materia, Date año, String semestre, String institucion, Set datossintesises) {
       this.academico = academico;
       this.materia = materia;
       this.año = año;
       this.semestre = semestre;
       this.institucion = institucion;
       this.datossintesises = datossintesises;
    }
   
    public Integer getIdexperienciaAcademica() {
        return this.idexperienciaAcademica;
    }
    
    public void setIdexperienciaAcademica(Integer idexperienciaAcademica) {
        this.idexperienciaAcademica = idexperienciaAcademica;
    }
    public Academico getAcademico() {
        return this.academico;
    }
    
    public void setAcademico(Academico academico) {
        this.academico = academico;
    }
    public String getMateria() {
        return this.materia;
    }
    
    public void setMateria(String materia) {
        this.materia = materia;
    }
    public Date getAño() {
        return this.año;
    }
    
    public void setAño(Date año) {
        this.año = año;
    }
    public String getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(String semestre) {
        this.semestre = semestre;
    }
    public String getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }
    public Set getDatossintesises() {
        return this.datossintesises;
    }
    
    public void setDatossintesises(Set datossintesises) {
        this.datossintesises = datossintesises;
    }




}


