package edu.uv.modelo.pojos.admproy;
// Generated 27/05/2014 12:50:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Experiencialaboral generated by hbm2java
 */
public class Experiencialaboral  implements java.io.Serializable {


     private Integer idexperienciaLaboral;
     private Academico academico;
     private String nomexperienciaLaboral;
     private String institucion;
     private String experienciaLaboralcol;
     private Set datossintesises = new HashSet(0);

    public Experiencialaboral() {
    }

	
    public Experiencialaboral(Academico academico, String nomexperienciaLaboral, String institucion, String experienciaLaboralcol) {
        this.academico = academico;
        this.nomexperienciaLaboral = nomexperienciaLaboral;
        this.institucion = institucion;
        this.experienciaLaboralcol = experienciaLaboralcol;
    }
    public Experiencialaboral(Academico academico, String nomexperienciaLaboral, String institucion, String experienciaLaboralcol, Set datossintesises) {
       this.academico = academico;
       this.nomexperienciaLaboral = nomexperienciaLaboral;
       this.institucion = institucion;
       this.experienciaLaboralcol = experienciaLaboralcol;
       this.datossintesises = datossintesises;
    }
   
    public Integer getIdexperienciaLaboral() {
        return this.idexperienciaLaboral;
    }
    
    public void setIdexperienciaLaboral(Integer idexperienciaLaboral) {
        this.idexperienciaLaboral = idexperienciaLaboral;
    }
    public Academico getAcademico() {
        return this.academico;
    }
    
    public void setAcademico(Academico academico) {
        this.academico = academico;
    }
    public String getNomexperienciaLaboral() {
        return this.nomexperienciaLaboral;
    }
    
    public void setNomexperienciaLaboral(String nomexperienciaLaboral) {
        this.nomexperienciaLaboral = nomexperienciaLaboral;
    }
    public String getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }
    public String getExperienciaLaboralcol() {
        return this.experienciaLaboralcol;
    }
    
    public void setExperienciaLaboralcol(String experienciaLaboralcol) {
        this.experienciaLaboralcol = experienciaLaboralcol;
    }
    public Set getDatossintesises() {
        return this.datossintesises;
    }
    
    public void setDatossintesises(Set datossintesises) {
        this.datossintesises = datossintesises;
    }




}


