package edu.uv.modelo.pojos.admproy;
// Generated 27/05/2014 12:50:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Idiomas generated by hbm2java
 */
public class Idiomas  implements java.io.Serializable {


     private Integer idIdiomas;
     private String nomIdioma;
     private float comprension;
     private float conversacion;
     private float traduccion;
     private Set academicos = new HashSet(0);
     private Set datossintesises = new HashSet(0);

    public Idiomas() {
    }

	
    public Idiomas(String nomIdioma, float comprension, float conversacion, float traduccion) {
        this.nomIdioma = nomIdioma;
        this.comprension = comprension;
        this.conversacion = conversacion;
        this.traduccion = traduccion;
    }
    public Idiomas(String nomIdioma, float comprension, float conversacion, float traduccion, Set academicos, Set datossintesises) {
       this.nomIdioma = nomIdioma;
       this.comprension = comprension;
       this.conversacion = conversacion;
       this.traduccion = traduccion;
       this.academicos = academicos;
       this.datossintesises = datossintesises;
    }
   
    public Integer getIdIdiomas() {
        return this.idIdiomas;
    }
    
    public void setIdIdiomas(Integer idIdiomas) {
        this.idIdiomas = idIdiomas;
    }
    public String getNomIdioma() {
        return this.nomIdioma;
    }
    
    public void setNomIdioma(String nomIdioma) {
        this.nomIdioma = nomIdioma;
    }
    public float getComprension() {
        return this.comprension;
    }
    
    public void setComprension(float comprension) {
        this.comprension = comprension;
    }
    public float getConversacion() {
        return this.conversacion;
    }
    
    public void setConversacion(float conversacion) {
        this.conversacion = conversacion;
    }
    public float getTraduccion() {
        return this.traduccion;
    }
    
    public void setTraduccion(float traduccion) {
        this.traduccion = traduccion;
    }
    public Set getAcademicos() {
        return this.academicos;
    }
    
    public void setAcademicos(Set academicos) {
        this.academicos = academicos;
    }
    public Set getDatossintesises() {
        return this.datossintesises;
    }
    
    public void setDatossintesises(Set datossintesises) {
        this.datossintesises = datossintesises;
    }




}


